import pandas as pd
from sqlalchemy import create_engine
import os
import sys

def run_ge_validation():
    print("Running Data Quality validation...")
    db_url = os.getenv("DATABASE_URL")
    if not db_url:
        raise RuntimeError(
            "DATABASE_URL environment variable is required. "
            "Set it to your PostgreSQL connection string."
        )
    engine = create_engine(db_url)
    
    try:
        # Read the features table generated by dbt
        df = pd.read_sql("SELECT * FROM public.fct_attrition_features", engine)
    except Exception as e:
        raise RuntimeError(f"Could not read from fct_attrition_features. Did dbt run successfully? Error: {e}")
        
    try:
        import great_expectations as gx
        ge_df = gx.from_pandas(df)
        
        checks = [
            # Core integrity
            ("years_at_company >= 0", ge_df.expect_column_values_to_be_between("years_at_company", min_value=0)),
            ("monthly_income > 0", ge_df.expect_column_values_to_be_between("monthly_income", min_value=1)),
            ("distance_from_home not null", ge_df.expect_column_values_to_not_be_null("distance_from_home")),
            # Referential integrity
            ("years_in_role <= years_at_company", ge_df.expect_column_pair_values_a_to_be_greater_than_b("years_at_company", "years_in_current_role", or_equal=True)),
            # Categorical cardinality
            ("over_time_yes in {0,1}", ge_df.expect_column_values_to_be_in_set("over_time_yes", [0, 1])),
            ("attrition in {0,1}", ge_df.expect_column_values_to_be_in_set("attrition", [0, 1])),
            ("travel_burden in {0,1,2}", ge_df.expect_column_values_to_be_in_set("travel_burden", [0, 1, 2])),
            # Engineered feature ranges
            ("engagement_index 1-4", ge_df.expect_column_values_to_be_between("engagement_index", min_value=1, max_value=4)),
            ("compa_ratio > 0", ge_df.expect_column_values_to_be_between("compa_ratio", min_value=0)),
            ("burnout_risk >= 0", ge_df.expect_column_values_to_be_between("burnout_risk", min_value=0)),
            ("promotion_stagnation >= 0", ge_df.expect_column_values_to_be_between("promotion_stagnation", min_value=0)),
            # Row count (detect empty or severely truncated tables)
            ("row_count >= 100", ge_df.expect_table_row_count_to_be_between(min_value=100)),
        ]
        
        failures = []
        for name, result in checks:
            status = "✓" if result["success"] else "✗"
            print(f"  {status} {name}")
            if not result["success"]:
                failures.append(name)
        
        if failures:
            raise ValueError(f"Data Quality checks FAILED: {', '.join(failures)}")
            
        print(f"All {len(checks)} Great Expectations checks passed!")
    except ImportError:
        print("Great Expectations not installed, falling back to Pandas assertions.")
        _pandas_fallback(df)
    except ValueError:
        raise
    except Exception as e:
        print(f"Great Expectations API changed or failed: {e}. Falling back to Pandas assertions.")
        _pandas_fallback(df)
        
    return True

def _pandas_fallback(df):
    """Comprehensive pandas-based validation when GE is unavailable."""
    errors = []
    if df["years_at_company"].min() < 0:
        errors.append("years_at_company has negative values")
    if df["monthly_income"].min() <= 0:
        errors.append("monthly_income <= 0 found")
    if df["distance_from_home"].isnull().sum() > 0:
        errors.append("distance_from_home contains nulls")
    if not df["over_time_yes"].isin([0, 1]).all():
        errors.append("over_time_yes has values outside {0, 1}")
    if not df["attrition"].isin([0, 1]).all():
        errors.append("attrition has values outside {0, 1}")
    if df["engagement_index"].min() < 1 or df["engagement_index"].max() > 4:
        errors.append("engagement_index outside [1, 4]")
    if (df["years_in_current_role"] > df["years_at_company"]).any():
        errors.append("years_in_current_role > years_at_company")
    if len(df) < 100:
        errors.append(f"Only {len(df)} rows — expected at least 100")
    
    if errors:
        raise ValueError(f"Data Quality Failed: {'; '.join(errors)}")
    print(f"All Pandas Data Quality checks passed! ({len(df)} rows)")

if __name__ == "__main__":
    run_ge_validation()

